/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_stephencao_jnireflectreview_JNIcCallJava */

#ifndef _Included_com_example_stephencao_jnireflectreview_JNIcCallJava
#define _Included_com_example_stephencao_jnireflectreview_JNIcCallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_stephencao_jnireflectreview_JNIcCallJava
 * Method:    callHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_stephencao_jnireflectreview_JNIcCallJava_callHello
  (JNIEnv *, jobject);

/*
 * Class:     com_example_stephencao_jnireflectreview_JNIcCallJava
 * Method:    callAddition
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_stephencao_jnireflectreview_JNIcCallJava_callAddition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_stephencao_jnireflectreview_JNIcCallJava
 * Method:    callPrint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_stephencao_jnireflectreview_JNIcCallJava_callPrint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_stephencao_jnireflectreview_JNIcCallJava
 * Method:    callFeedBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_stephencao_jnireflectreview_JNIcCallJava_callFeedBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
